FROM node:16-alpine

RUN apk update
RUN apk add --no-cache \
  chromium \
  ffmpeg \
  libc6-compat

WORKDIR /app

COPY package.json package*.json yarn.lock* pnpm-lock.yaml* bun.lockb* tsconfig.json* remotion.config.* ./
COPY src ./src

RUN npm i
RUN rm -rf node_modules/@remotion/renderer/dist
RUN ls node_modules

ADD tmp-renderer-package ./node_modules/@remotion/renderer/dist


# Run your application
COPY render.mjs render.mjs
CMD ["node", "render.mjs"]
